Repository CSE-110-Group-13/warm-up, pull requests merged in 2024-04, with the labels that each got.

#5 Calendar implementation using lists
  calendar-for-navigation/test.css
  calendar-for-navigation/test.html
  calendar-for-navigation/test.js
Labels: bug, documentation, enhancement, help wanted

#12 # Add styling to the calendar
  calendar-for-navigation/favicon.ico
  calendar-for-navigation/test.css
  calendar-for-navigation/test.html
Labels: documentation

#26 Fixed translate and added footers
  calendar-for-navigation/index.html
  task-list/index.html
Labels: bug, enhancement
